# Generated by Django 4.2.7 on 2024-08-07 04:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_under_test', models.TextField()),
                ('llm_output', models.TextField()),
                ('criteria', models.TextField()),
                ('auto_eval', models.IntegerField()),
                ('auto_feedback', models.TextField()),
            ],
        ),
    ]
